### ISSUE TITLE
LinknoidBarf pre-adventure item prep

### ISSUE THREAD

**Issue by gausie** [linknoid/MafiaScripts#2]
Would be good to have a step that:

- makes sure you have a print screen button
- sets boombox to Total Eclipse
- makes sure can of rain-doh is opened

etc etc

**Comment by linknoid** [comment]
Sorry I didn't notice this for so long, I don't log into the GitHub website that often.

The rain-doh used to work, but broke when I commented out some code.  It should be working now.

I added a Set boombox to "Total Eclipe of Your Meat" prompt at the beginning, happens automatic if you auto-confirm.

I'm not sure what you want the print screen button to do, but it shouldn't be trying to use one if you don't have it.  You could technically spend all your turns burning through print screens, so I implemented using 1 a day to turn the Infinite BACON machine into a 30k drop each day, but it's probably better to set it to 0, since the print screen is worth more than you'll earn from copying an embezzler.
